name: Create and publish a Docker image to hub.docker.com

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'henriksson-lab/shiny_barseq'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mahogny83/shiny_barseq
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: "20240122-183100"
